# import aws parameter store
spring.config.import=aws-parameterstore:/gochang/

# disable aws stack auto(for lightsqil use)
cloud.aws.stack.auto=false

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# change json properties' name into snake case
spring.jackson.property-naming-strategy=SNAKE_CASE
